### ISSUE TITLE
elm-app build command is failing

### ISSUE THREAD

**Issue by kevgathuku** [halfzebra/create-elm-app#127]
Hello,
I'm using the `elm-app` tool to build a production build on Heroku and it fails with the following error:
```
Starting production build...
remote:
remote:        /tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/create-elm-app/scripts/build.js:19
remote:        if (stats.compilation.errors.length > 0) {
remote:        ^
remote:
remote:        TypeError: Cannot read property 'compilation' of undefined
remote:        at webpack.run (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/create-elm-app/scripts/build.js:19:12)
remote:        at onCompiled (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/webpack/lib/Compiler.js:232:21)
remote:        at /tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/webpack/lib/Compiler.js:484:19
remote:        at /tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/tapable/lib/Tapable.js:221:11
remote:        at _addModuleChain (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/webpack/lib/Compilation.js:468:12)
remote:        at processModuleDependencies.err (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/webpack/lib/Compilation.js:445:14)
remote:        at finalCallbackAddModuleDependencies (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/webpack/lib/Compilation.js:351:12)
remote:        at /tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/async/dist/async.js:421:16
remote:        at iteratorCallback (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/async/dist/async.js:996:13)
remote:        at /tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/async/dist/async.js:906:16
remote:        at finalCallbackAddModuleDependencies (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/webpack/lib/Compilation.js:351:12)
remote:        at /tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/async/dist/async.js:421:16
remote:        at iteratorCallback (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/async/dist/async.js:996:13)
remote:        at /tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/async/dist/async.js:906:16
remote:        at errorAndCallback (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/webpack/lib/Compilation.js:217:6)
remote:        at errorOrWarningAndCallback (/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/node_modules/webpack/lib/Compilation.js:247:14)
remote:
remote:        npm ERR! Linux 3.13.0-112-generic
remote:        npm ERR! argv "/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/.heroku/node/bin/node" "/tmp/build_8b9185c204b28f464c5bf2e998f92e5f/.heroku/node/bin/npm" "run" "build"
remote:        npm ERR! node v6.10.3
remote:        npm ERR! npm  v3.10.10
```

I'm not sure how to fix it. Any help would be very much appreciated. Thanks!

**Comment by kevgathuku** [comment]
From the source, it seems the [`build` command](https://github.com/halfzebra/create-elm-app/blob/master/scripts/build.js#L18) is using the webpack 1 API  (http://webpack.github.io/docs/node.js-api.html#the-long-way) and the package depends on webpack 2.3.3.

**Comment by kevgathuku** [comment]
I got this fixed by ejecting the tool and running the generated `build.js` script directly. Worked like a charm 😄

**Comment by EvertYipYip** [comment]
Please reopen, I have the same problem in a docker containter elm and create-elm app installed globally

**Comment by kevgathuku** [comment]
@EvertYipYip does ejecting the tool still cause the same problem?

**Comment by EvertYipYip** [comment]
@kevgathuku did not test that yet. But in my opinion that isn't a robust solution. Yes I will be able to build my tool then, But it doen't fix the bug with create-elm-app

**Comment by halfzebra** [comment]
@EvertYipYip thanks for reopening the issue!

It should work as a local dependency, we'll look into that shortly 🙂
