### ISSUE TITLE
Multiple %PUBLIC_URL% in same file are not processed

### ISSUE THREAD

**Issue by perty** [halfzebra/create-elm-app#248]
### Is this a bug report?
Yes

### Environment

1. `node -v`:
v6.10.2
2. `npm -v`:
4.2.0
3. `yarn --version` (if you use Yarn):
4. `npm ls create-elm-app -g` (if you haven’t ejected):
/usr/local/lib
└── create-elm-app@1.10.2

Then, specify:

1. Operating system:
Mac
2. Browser and version (if relevant):
N/A

### Steps to Reproduce

(Write your steps here:)

1. create-elm-app
2. Add two references to %PUBLIC_URL% e.g.
        , div [ class "menu", onClick (Msg.FollowRoute Model.BrfListRoute) ]
            [ img [ src "%PUBLIC_URL%/brflist.png" ] [] ]
        , div [ class "menu", onClick (Msg.FollowRoute Model.InfoRoute) ]
            [ img [ src "%PUBLIC_URL%/info.png" ] [] ]
3. elm start

### Expected Behavior

The %PUBLIC_URL% should be replaced in both places

### Actual Behavior

Output:
URIError: Failed to decode param '/add/%PUBLIC_URL%/info.png'
    at decodeURIComponent (native)
    at decode_param (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:574:18)
    at next (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:317:13)
    at /usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/lib/node_modules/create-elm-app/node_modules/express/lib/router/index.js:335:12)
        

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by perty** [comment]
I should add that if there is only one PUBLIC_URL, it works fine.

**Comment by halfzebra** [comment]
Hi @perty, thanks for reporting this bug!

The fix is on the way #249
