### ISSUE TITLE
 Error: EEXIST: file already exists, mkdir 'C:\dev\elm\my-app'

### ISSUE THREAD

**Issue by MichaelHipp** [halfzebra/create-elm-app#25]
Getting this error when creating an app on Windows 10 x64. The folder 'my-app' definitely did not exist beforehand.
```
[michael.mrh-laptop] ➤ create-elm-app my-app

Creating my-app project...

{ Error: EEXIST: file already exists, mkdir 'C:\dev\elm\my-app'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.mkdirsSync (C:\Users\michael\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:29:9)
    at copySync (C:\Users\michael\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:31:36)
    at C:\Users\michael\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:40:7
    at Array.forEach (native)
    at copySync (C:\Users\michael\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\fs-extra\lib\copy-sync\copy-sync.js:37:14)
    at createElmApp (C:\Users\michael\AppData\Roaming\npm\node_modules\create-elm-app\scripts\create.js:30:7)
    at Object.<anonymous> (C:\Users\michael\AppData\Roaming\npm\node_modules\create-elm-app\scripts\create.js:18:1)
    at Module._compile (module.js:556:32)
  errno: -4075,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: 'C:\\dev\\elm\\my-app' }

```

**Comment by MichaelHipp** [comment]
When I tried making the project in a different subdir ( `c:\dev\foo` instead of `c:\dev\elm` ) it worked fine. Seems to be some sort of permissions issue and I think this not a problem with `create-elm-app` but something on my system. Closing.
