### ISSUE TITLE
Trying to run create-elm-app on Linux Mint

### ISSUE THREAD

**Issue by j-panasiuk** [halfzebra/create-elm-app#26]
I recently switched from Win7 to Linux Mint (18) and now keep running into strange errors

Firstly, **create-elm-app <name>** creates proper folder structure, but doesn't download any packages (nor does it create elm-package.json file)

If I then use **elm package install** by hand, everything loads as expected. However, on **elm-app start** (and other commands too) I get following error:
```
Compilation failed.

./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/lib/node_modules/create-elm-app/node_modules/elm/Elm-Platform/0.17.1/.cabal-sandbox/bin/elm-make ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3

    at ChildProcess.<anonymous> (/usr/lib/node_modules/create-elm-app/node_modules/elm-webpack-loader/node_modules/node-elm-compiler/index.js:224:27)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
 @ ./src/index.js 3:10-31
```
I noticed that **/usr/lib/node_modules/create-elm-app/node_modules/elm** folder doesn't actually contain **Elm-Platform**. I don't know if it's more nodejs+linux than create-elm-app problem. Maybe someone will have an idea how to fix this?
Just for reference
node: 4.6.0
npm: 2.15.9

**Comment by halfzebra** [comment]
Hello @j-panasiuk!

Thank you for reporting the issue, I think this might be a duplicate of #10

**Comment by j-panasiuk** [comment]
yes, that helped - Elm binaries were missing from this folder
thanks!

**Comment by pzingg** [comment]
Just to be clear the "sudo npm run install" command should be done in the **/usr/lib/node_modules/create-elm-app/node_modules/elm** folder, correct?

**Comment by halfzebra** [comment]
@pzingg yes, alternatively you can install Create Elm App with `sudo`, that should work as well.

```sh
 sudo npm install create-elm-app -g
```

**Comment by rmoorman** [comment]
I have been able to install en use create-elm-app on Linux Mint without using sudo (luckily) ... I just had to fiddle with some npm/node related settings/environment variables as decribed [here](https://topaxi.codes/use-npm-without-root-or-sudo-rights/) or [here](https://devin-clark.com/global-npm-install-without-sudo.html)
