### ISSUE TITLE
Error when creating new app

### ISSUE THREAD

**Issue by alanbar** [halfzebra/create-elm-app#68]
I'm using Ubuntu 14.04.
I do 'sudo npm install create-elm-app -g' and get 'Project is successfully created in `/home/alan/jack`.'
I do 'cd jack' and then 'elm-app start' and get following terminal message....

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at Server.listen (/usr/local/lib/node_modules/create-elm-app/node_modules/webpack-dev-server/lib/Server.js:324:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-elm-app/scripts/start.js:62:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

Local host:3000 gives 'Uncaught ReferenceError: _elm_lang$virtual_dom$VirtualDom$programWithFlags is not defined(…)

Help please.

**Comment by halfzebra** [comment]
@alanbar looks like you have something running on `localhost:3000`, I'll add an option to change the default port in the next release.

**Comment by alanbar** [comment]
Local host : 3000 message also shows 'webpack:///./src/Main.elm?' and if I double click on this, I get an External Protocol request message saying 'xdg-open' will be launched if I click the button.
When I do this, the message disappears but no output from Elm is showing.

**Comment by peterszerzo** [comment]
Now that we have support for environment variables specified in `.env`, should we just pick up on the PORT variable?

**Comment by halfzebra** [comment]
@peterszerzo this makes perfect sense for overwriting the default value, but the problem still stands for the use-case from this specific issue.

**Comment by halfzebra** [comment]
#36 is done.

I'm closing this issue 🎉
