### ISSUE TITLE
Package stopped working

### ISSUE THREAD

**Issue by gyzerok** [halfzebra/create-elm-app#91]
Right now if you do fresh installation of the package, it does not work.

```
npm rm -g create-elm-app
npm i -g create-elm-app
elm-app create test
cd test
elm-app start
```

```
$ elm-app start
/Users/fnez/.nvm/versions/node/v4.5.0/lib/node_modules/create-elm-app/bin/elm-app-cli.js:29
    if (pathExists.sync('elm-package.json') === false) {
        ^

ReferenceError: pathExists is not defined
    at Object.<anonymous> (/Users/fnez/.nvm/versions/node/v4.5.0/lib/node_modules/create-elm-app/bin/elm-app-cli.js:29:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

**Comment by gyzerok** [comment]
I am not sure in what release this issue were introduce and do not really remember what version I was using previously.

Here is one which installs by default now.
```
$ elm-app --help

Usage: elm-app <command>

where <command> is one of:
    create, build, start, package, reactor, make, repl


Elm 0.18.0

create-elm-app@0.2.1 /Users/fnez/.nvm/versions/node/v4.5.0/lib/node_modules/create-elm-app
```

**Comment by gyzerok** [comment]
If I do install 0.2.4 then following error occur after starting:

```
Compilation failed.

Error in Cannot find module 'glob'
 @ ./src/index.js 3:10-31
```

**Comment by gyzerok** [comment]
As of my current understanding this happens when you install with npm < 3.0

**Comment by halfzebra** [comment]
@gyzerok thanks for reporting this,

I think we're not going to support npm below version 3 😕

**Comment by gyzerok** [comment]
@halfzebra so we then at least should be mentioned somehow, because it is not clear that the issue is caused by old npm version. Maybe some troubleshooting section?

**Comment by bardt** [comment]
Same issue here. Probably we could check the npm version on install/start to avoid such indirection?
